name: Trigger Automation Tests

on:
  push:
    branches:
      - main

jobs:
  trigger-automation:
    runs-on: ubuntu-latest
    steps:
      - name: Send a dispatch to trigger automation tests
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
            https://api.github.com/repos/narayanaswamy-tg-tft/Livelike_Assignment/dispatches \
            -d '{"event_type":"trigger-tests"}'
